services:
  - type: web
    name: jef-yoon
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    disk:
      name: laravel-storage
      mountPath: /var/www/html/storage
      sizeGB: 1
    envVars:
      - key: APP_NAME
        value: "Jëf & Yoon"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: "base64:f5VLXsH2P6tucap2X8m3MFFStzNxc7UOAYdPBgldJw4="
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://jef-yoon.onrender.com"
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: "/var/www/html/storage/app/database.sqlite"
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stack
